DROP TABLE IF EXISTS HASHBLOCKS;

CREATE TABLE HASHBLOCKS (
  ID INT NOT NULL AUTO_INCREMENT,
  HASHDATA VARCHAR(255) NOT NULL,
  PARENTHASH VARCHAR(255) NOT NULL,
  CAPTIONDATA VARCHAR(255),
  PRIMARY KEY (ID)
);

INSERT INTO HASHBLOCKS (ID, HASHDATA, PARENTHASH, CAPTIONDATA) VALUES
  (1, 'testHash', '0000', 'test caption')