DROP TABLE IF EXISTS HASHBLOCKS;

CREATE TABLE HASHBLOCKS (
  ID INT NOT NULL AUTO_INCREMENT,
  HASHDATA VARCHAR(255) NOT NULL,
  PARENTHASH VARCHAR(255) NOT NULL,
  CAPTIONDATA VARCHAR(255),
  NONCE INT NOT NULL,
  WORKPROVEN BIT,
  BLOCKTIME BIGINT,
  PRIMARY KEY (ID)
);